#
# Author: Eduardo Hernandez
# Class: CSc 110
# Description: This program will display a screen with graphics on it. The graphics
# will move with the user's cursor but at different rates. The further back objects
# will move much slower than the objects at the forefront. Enjoy!
#

# Imports the graphics module from graphics.py
from graphics import graphics
# Imports random to be used for the random colors for the mountains
import random


def middle_mountain(gui, color_1):
    '''
    This function generates the middle mountain in the background.
    gui: This calls the graphics module.
    color_1: This color is generated by a randomizer in the main function.
    return: the middle mountain.
    '''
    # These x and y values are what determine the speed of which the mountain moves
    x = (gui.mouse_x / 15) + 375
    y = (gui.mouse_y / 15) + 375
    # This prints out the triangular mountain
    gui.triangle(x - 290, y + 375, x - 25, y - 225, x + 275, y + 375, color_1)


def side_mountains(gui, color_2, color_3):
    '''
    This function generates the side mountains in the background.
    gui: This calls the graphics module
    color_2: This color is generated by a randomizer in the main function.
    color_3: This color is generated by a randomizer in the main function.
    return: The side mountains
    '''
    # These x and y values are what determine the speed of which the mountains move
    x = (gui.mouse_x/8) + 325
    y = (gui.mouse_y/8) + 325
    # These print out the mountains
    gui.triangle(x - 525, y + 375, x - 175, y - 125, x + 175, y + 375, color_2)
    gui.triangle(x + 525, y + 375, x + 175, y - 125, x - 225, y + 375, color_3)


def sun(gui):
    '''
    This function generates the sun all the way in the back
    gui: This calls the graphics module
    return: The sun
    '''
    # These x and y values are what determine the speed of which the sun moves
    x = (gui.mouse_x/20) + 375
    y = (gui.mouse_y/20) + 375
    # This prints out the sun
    gui.ellipse(x + 150, y - 290, 100, 100, "yellow")


def foreground(gui):
    '''
    This function generates the grass blades, the grass plain, the tree and birds.
    gui: calls the graphics module
    return: The grass blades, grass plain, tree, and birds
    '''
    # These x and y values are what determine the speed of which the foreground moves
    # besides the birds
    x = (gui.mouse_x/4) + 250
    y = (gui.mouse_y/4) + 250
    # This prints out grass plain
    gui.rectangle(x - 500, y + 275, 1000, 300, "green")
    # This while loop prints each blade of grass
    i = -100
    while i <= 900:
        gui.line((x - 375) + i, y + 225, (x - 375) + i, y + 275, "green", 5)
        i += 10
    # These print out the tree
    gui.line(x + 125, y + 125, x + 125, y + 325, "brown", 40)
    gui.ellipse(x + 125, y + 175, 100, 150, "green")
    # This while loop prints out the birds
    index = -50
    while index <= 500:
        gui.line(0 + index, 15 + (index / 3), 25 + index, 30 + (index / 3), "black", 5)
        gui.line(24 + index, 30 + (index / 3), 49 + index, 15 + (index / 3), "black", 5)
        index += 100


def monkey(gui):
    '''
    This function generates the monkey in the foreground
    gui: calls the graphics module
    return: the monkey
    '''
    # These x and y values are what determine the speed of which the monkey moves
    x = (gui.mouse_x / 4) + 275
    y = (gui.mouse_y / 4) + 275
    # These are my custom brown colors
    brown = gui.get_color_string(102, 64, 21)
    light_brown = gui.get_color_string(186, 142, 91)
    # The rest of these prints out the monkey
    gui.ellipse(x - 67, y + 178, 30, 30, brown)
    gui.ellipse(x - 32, y + 178, 30, 30, brown)
    gui.ellipse(x - 67, y + 178, 20, 20, light_brown)
    gui.ellipse(x - 32, y + 178, 20, 20, light_brown)
    gui.ellipse(x - 50, y + 200, 50, 60, brown)
    gui.ellipse(x - 60, y + 205, 22, 50, light_brown)
    gui.ellipse(x - 40, y + 205, 22, 50, light_brown)
    gui.ellipse(x - 50, y + 250, 40, 60, brown)
    gui.ellipse(x - 50, y + 250, 27, 45, light_brown)
    gui.line(x - 35, y + 235, x - 15, y + 215, brown, 5)
    gui.line(x - 65, y + 235, x - 80, y + 255, brown, 5)
    gui.line(x - 60, y + 275, x - 70, y + 290, brown, 5)
    gui.line(x - 70, y + 289, x - 68, y + 305, brown, 5)
    gui.line(x - 40, y + 275, x - 30, y + 290, brown, 5)
    gui.line(x - 30, y + 289, x - 32, y + 305, brown, 5)
    gui.line(x - 40, y + 265, x - 25, y + 277, brown, 5)
    gui.line(x - 27, y + 277, x - 12, y + 277, brown, 5)
    gui.line(x - 12, y + 277, x - 4, y + 260, brown, 4)
    gui.line(x - 4, y + 262, x - 17, y + 250, brown, 3)
    gui.line(x - 17, y + 250, x - 25, y + 260, brown, 2)
    gui.line(x - 24, y + 260, x - 19, y + 265, brown, 1)
    gui.ellipse(x - 50, y + 215, 50, 30, light_brown)
    gui.ellipse(x - 50, y + 210, 20, 10, brown)
    gui.ellipse(x - 60, y + 190, 10, 10, "black")
    gui.ellipse(x - 40, y + 190, 10, 10, "black")
    gui.ellipse(x - 61, y + 188, 3, 3, "white")
    gui.ellipse(x - 41, y + 188, 3, 3, "white")
    gui.line(x - 65, y + 220, x - 35, y + 220, "black", 2)
    gui.line(x - 36, y + 220, x - 30, y + 215, "black", 2)
    gui.line(x - 64, y + 220, x - 70, y + 215, "black", 2)


def main():
    gui = graphics(750, 750, 'Motion Parallax')
    # This code generates the random colors that each individual mountain will be
    color_1 = gui.get_color_string(random.randint(0, 255), random.randint(0, 255),
                                   random.randint(0, 255))
    color_2 = gui.get_color_string(random.randint(0, 255), random.randint(0, 255),
                                   random.randint(0, 255))
    color_3 = gui.get_color_string(random.randint(0, 255), random.randint(0, 255),
                                   random.randint(0, 255))
    # This displays the entire drawing
    while True:
        gui.clear()
        gui.rectangle(-50, -50, 800, 800, 'light blue')
        sun(gui)
        middle_mountain(gui, color_1)
        side_mountains(gui, color_2, color_3)
        foreground(gui)
        monkey(gui)
        gui.update_frame(60)


main()
